version: '3.3'

services:
 traefik:
    # The official v3.6 Traefik docker image
    image: traefik:v3.6
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      - ACME_EMAIL=${ACME_EMAIL}
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      #- "--api.insecure=true"
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myhttpchallenge.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
      - target: 80
        published: 80
        mode: host
      # Listen on port 443, default for HTTPS
      - target: 443
        published: 443
        mode: host
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      - traefik-public

 # The error pages server
 error:
   image: nginx:latest
   networks:
     - traefik-public
   volumes:
     - ./error-pages:/usr/share/nginx/html
     - ./error.conf:/etc/nginx/conf.d/default.conf
   deploy:
     labels:
       - 'traefik.enable=true'
       - 'traefik.http.routers.error.rule=HostRegexp(`{host:.+}`)'
       - 'traefik.http.routers.error.entrypoints=web'
       - 'traefik.http.routers.error.priority=1'
       - 'traefik.http.services.error.loadbalancer.server.port=80'
       - 'traefik.http.routers.error.middlewares=error-pages-middleware'
       - 'traefik.http.middlewares.error-pages-middleware.errors.status=400-599'
       - 'traefik.http.middlewares.error-pages-middleware.errors.service=error'
       - 'traefik.http.middlewares.error-pages-middleware.errors.query=/{status}.html'

networks:
  traefik-public:
    external: true
